package com.delivery.tracking.domain;

import java.time.Duration;
import java.time.Instant;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * One row per rider, holding their declared duty state and their last known fix.
 *
 * <p>The durable half of presence. Redis caches the same snapshot under a TTL for the hot read, but
 * this row is the record — a cache flush must not take a whole fleet off duty, and a rider halfway
 * through a delivery must still be on the roster after a service restart.
 *
 * <p>Updated in place, never appended to. That is what keeps presence bounded at one row per rider
 * however long the platform runs, and is why nothing here needs partitioning; see V12 for the
 * fuller argument, including why an idle rider's breadcrumb trail is deliberately not kept.
 *
 * <p>The PostGIS {@code last_location} column is generated by the database from the lat/lng pair
 * and is not mapped here, exactly as on {@link TrackingEvent} and for the same reasons.
 */
@Entity
@Table(name = "rider_presence")
public class RiderPresence {

    @Id
    @Column(name = "rider_id", nullable = false, updatable = false, length = 64)
    private String riderId;

    /** The fleet this rider carries for, or null for the platform's own riders. */
    @Column(name = "carrier_id")
    private UUID carrierId;

    @Enumerated(EnumType.STRING)
    @Column(name = "duty_state", nullable = false, length = 16)
    private DutyState dutyState;

    @Column(name = "duty_changed_at", nullable = false)
    private Instant dutyChangedAt;

    /** When the last fix arrived. Null for a rider who has declared duty but never pinged. */
    @Column(name = "last_seen_at")
    private Instant lastSeenAt;

    @Column(name = "last_lat")
    private Double lastLat;

    @Column(name = "last_lng")
    private Double lastLng;

    @Column(name = "last_accuracy_m")
    private Float lastAccuracyM;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    protected RiderPresence() {
        // for JPA
    }

    private RiderPresence(String riderId, DutyState dutyState, Instant now) {
        this.riderId = riderId;
        this.dutyState = dutyState;
        this.dutyChangedAt = now;
        this.updatedAt = now;
    }

    /**
     * A rider we have only ever seen a location from.
     *
     * <p>Starts OFF_DUTY, and that is not a detail: a GPS fix is not a declaration of availability.
     * A rider whose app is open on the way home would otherwise be handed a job by dispatch. It is
     * also why the first duty declaration a rider ever makes is a real transition from this state
     * and gets logged as one.
     */
    public static RiderPresence firstSeen(String riderId, Instant now) {
        return new RiderPresence(riderId, DutyState.OFF_DUTY, now);
    }

    /**
     * Records a duty declaration.
     *
     * <p>{@code dutyChangedAt} only moves when the state actually changes. A rider tapping "go
     * online" twice, or an app that re-asserts duty on every foreground, must not keep resetting
     * the clock that says how long this shift has been running.
     */
    public void declare(DutyState state, Instant now) {
        if (this.dutyState != state) {
            this.dutyState = state;
            this.dutyChangedAt = now;
        }
        this.updatedAt = now;
    }

    /** Records a fix. Says nothing about duty — a location is evidence of life, not of consent. */
    public void sighted(double lat, double lng, Float accuracyM, Instant now) {
        this.lastLat = lat;
        this.lastLng = lng;
        this.lastAccuracyM = accuracyM;
        this.lastSeenAt = now;
        this.updatedAt = now;
    }

    /**
     * Learned from an order this rider carried for a fleet.
     *
     * <p>Only ever set, never cleared, because the source that tells us is an order event and an
     * order event that omits the provider means "the platform's own fleet took this one", not "this
     * rider has left the company".
     */
    public void attachCarrier(UUID carrierId, Instant now) {
        if (carrierId != null && !carrierId.equals(this.carrierId)) {
            this.carrierId = carrierId;
            this.updatedAt = now;
        }
    }

    /**
     * Whether this rider is genuinely reachable, judged against a presence window.
     *
     * <p>The stale case is the reason this method exists. Trusting {@code duty_state} alone would
     * leave a rider with a dead phone on the roster indefinitely, and dispatch would keep offering
     * them work that nothing is going to collect.
     */
    public PresenceState effectiveState(Instant now, Duration presenceWindow) {
        if (dutyState != DutyState.ON_DUTY) {
            return PresenceState.OFF_DUTY;
        }
        if (lastSeenAt == null || lastSeenAt.isBefore(now.minus(presenceWindow))) {
            return PresenceState.STALE;
        }
        return PresenceState.ON_DUTY;
    }

    public String getRiderId() {
        return riderId;
    }

    public UUID getCarrierId() {
        return carrierId;
    }

    public DutyState getDutyState() {
        return dutyState;
    }

    public Instant getDutyChangedAt() {
        return dutyChangedAt;
    }

    public Instant getLastSeenAt() {
        return lastSeenAt;
    }

    public Double getLastLat() {
        return lastLat;
    }

    public Double getLastLng() {
        return lastLng;
    }

    public Float getLastAccuracyM() {
        return lastAccuracyM;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
