/*
  A QR encoder, small enough to read in one sitting.

  Written here rather than vendored. The alternatives were a third-party bundle (a dependency, a
  licence header and a supply chain, for one static URL) or a hosted image service (an outbound
  request from the landing page to somebody else's server, which is both a privacy leak and a
  single point of failure for the one thing on the page that has to work offline). This is the
  smallest honest third option: about three hundred lines of ISO/IEC 18004 that never leaves the
  browser.

  © 2026 YouDrop Technologies Inc. Original work, written for this repository. The specification it
  implements — ISO/IEC 18004, "QR Code bar code symbology" — is a standard, not a licensed library:
  nothing here is copied from another implementation, so nothing here carries another licence.

  ------------------------------------------------------------------------------------------------
  WHAT IT DOES AND, MORE USEFULLY, WHAT IT DOES NOT

  Byte mode only, versions 1 to 4, and only the (version, correction level) pairs whose data fits in
  a SINGLE error-correction block. That last restriction is the interesting one.

  A QR symbol above a certain size splits its data across several blocks, each with its own parity,
  and then interleaves the blocks codeword by codeword so that a coffee stain damages a little of
  each rather than all of one. Interleaving is not hard, but it is driven by a table of block counts
  covering forty versions and four correction levels — a hundred and sixty numbers that cannot be
  checked by looking at the picture, because a symbol built from a wrong block count still LOOKS
  like a QR code and simply refuses to scan. Rather than transcribe that table from memory and hope,
  this file carries only the eleven combinations that need no table at all, verifies them against
  the total-codeword count for their version, and throws a plain error for anything longer.

  The ceiling depends on how much correction is asked for: 14 bytes at H, 20 at Q, 42 at M and 78
  at L. The URL this page encodes is 28, so it lands on version 3 at level M with room to spare. If
  a longer string is ever needed here, add the block table and the interleaving loop; do not quietly
  widen the bounds below, because the failure mode is a code that looks perfect and scans on nothing.
  ------------------------------------------------------------------------------------------------
*/

(function (global) {
  'use strict';

  // ---------------------------------------------------------------- GF(256)

  /*
    Reed-Solomon runs over the field GF(256) generated by x^8 + x^4 + x^3 + x^2 + 1 (0x11D), which
    is the polynomial the QR specification names. Multiplication becomes addition of logarithms, so
    two 256-entry tables replace every multiply below. EXP is doubled in length so a sum of two
    logarithms (each at most 254) can be looked up without a modulo.
  */
  var EXP = new Uint8Array(512);
  var LOG = new Uint8Array(256);
  (function () {
    var x = 1;
    for (var i = 0; i < 255; i++) {
      EXP[i] = x;
      LOG[x] = i;
      x <<= 1;
      if (x & 0x100) x ^= 0x11D;
    }
    for (var j = 255; j < 512; j++) EXP[j] = EXP[j - 255];
  })();

  function mul(a, b) {
    return (a === 0 || b === 0) ? 0 : EXP[LOG[a] + LOG[b]];
  }

  /** The generator polynomial for `degree` error-correction codewords, highest power first. */
  function generatorPoly(degree) {
    var g = [1];
    for (var i = 0; i < degree; i++) {
      // Multiply by (x + α^i).
      var next = new Array(g.length + 1);
      for (var k = 0; k < next.length; k++) next[k] = 0;
      for (var j = 0; j < g.length; j++) {
        next[j] ^= g[j];
        next[j + 1] ^= mul(g[j], EXP[i]);
      }
      g = next;
    }
    return g;
  }

  /** The remainder of `data` divided by the generator — i.e. the parity codewords. */
  function remainder(data, degree) {
    var g = generatorPoly(degree);
    var rem = new Uint8Array(degree);
    for (var i = 0; i < data.length; i++) {
      var factor = data[i] ^ rem[0];
      rem.copyWithin(0, 1);
      rem[degree - 1] = 0;
      if (factor !== 0) {
        for (var j = 0; j < degree; j++) rem[j] ^= mul(g[j + 1], factor);
      }
    }
    return rem;
  }

  // ---------------------------------------------------------------- the symbol table

  /*
    [version][level] -> [data codewords, error-correction codewords], for the single-block
    combinations only. The two always add up to the version's total codeword count, which is
    asserted at load time below: a typo in this table is the one mistake that produces a symbol
    which looks right and scans on nothing.
  */
  /** The two-bit field written into the format information — not the strength order, deliberately. */
  var LEVEL_BITS = { L: 1, M: 0, Q: 3, H: 2 };

  var BLOCKS = {
    1: { L: [19, 7], M: [16, 10], Q: [13, 13], H: [9, 17] },
    2: { L: [34, 10], M: [28, 16], Q: [22, 22], H: [16, 28] },
    3: { L: [55, 15], M: [44, 26] },
    4: { L: [80, 20] }
  };

  /** Total codewords per version (data + error correction), from the specification. */
  var TOTAL_CODEWORDS = { 1: 26, 2: 44, 3: 70, 4: 100 };

  /** Alignment-pattern centre coordinates per version. Version 1 has none. */
  var ALIGNMENT = { 1: [], 2: [6, 18], 3: [6, 22], 4: [6, 26] };

  (function selfCheck() {
    for (var version in BLOCKS) {
      for (var level in BLOCKS[version]) {
        var pair = BLOCKS[version][level];
        if (pair[0] + pair[1] !== TOTAL_CODEWORDS[version]) {
          throw new Error('qr.js: version ' + version + level + ' does not add up');
        }
      }
    }
  })();

  // ---------------------------------------------------------------- bit stream

  function BitStream() {
    this.bits = [];
  }
  BitStream.prototype.push = function (value, length) {
    for (var i = length - 1; i >= 0; i--) this.bits.push((value >>> i) & 1);
  };

  // ---------------------------------------------------------------- encoding

  /** UTF-8 bytes. The URL this page encodes is ASCII, but nothing here assumes that. */
  function toBytes(text) {
    if (typeof TextEncoder === 'function') return new TextEncoder().encode(text);
    var out = [];
    for (var i = 0; i < text.length; i++) {
      var c = text.charCodeAt(i);
      if (c < 0x80) {
        out.push(c);
      } else if (c < 0x800) {
        out.push(0xC0 | (c >> 6), 0x80 | (c & 0x3F));
      } else {
        out.push(0xE0 | (c >> 12), 0x80 | ((c >> 6) & 0x3F), 0x80 | (c & 0x3F));
      }
    }
    return new Uint8Array(out);
  }

  /**
   * The smallest symbol that holds `byteCount` bytes at `level` or better.
   *
   * Tried smallest-first so the code stays as coarse as it can — a larger symbol in the same 100px
   * tile means smaller modules, and smaller modules are what a phone camera fails on.
   */
  function chooseSymbol(byteCount, level) {
    var wanted = 4 + 8 + byteCount * 8;                 // mode + length + payload, in bits
    var needed = Math.ceil(wanted / 8);
    var order = ['H', 'Q', 'M', 'L'];
    var floor = order.indexOf(level);
    if (floor < 0) throw new Error('qr.js: unknown correction level ' + level);

    for (var version = 1; version <= 4; version++) {
      // Best correction first, so a payload that happens to fit at a stronger level gets it free.
      for (var i = 0; i <= floor; i++) {
        var candidate = BLOCKS[version][order[i]];
        if (candidate && candidate[0] >= needed) {
          return { version: version, level: order[i], data: candidate[0], ec: candidate[1] };
        }
      }
    }
    throw new Error('qr.js: ' + byteCount + ' bytes will not fit at correction level ' + level
        + ' (the single-block ceiling is 14 at H, 20 at Q, 42 at M, 78 at L)');
  }

  function codewords(bytes, symbol) {
    var stream = new BitStream();
    stream.push(0b0100, 4);            // byte mode
    stream.push(bytes.length, 8);      // character count, 8 bits for versions 1-9
    for (var i = 0; i < bytes.length; i++) stream.push(bytes[i], 8);

    var capacity = symbol.data * 8;
    // Terminator: up to four zero bits, fewer if the symbol is nearly full.
    stream.push(0, Math.min(4, capacity - stream.bits.length));
    // Then to a byte boundary.
    while (stream.bits.length % 8 !== 0) stream.bits.push(0);

    var out = new Uint8Array(symbol.data);
    for (var b = 0; b < stream.bits.length; b += 8) {
      var value = 0;
      for (var k = 0; k < 8; k++) value = (value << 1) | stream.bits[b + k];
      out[b / 8] = value;
    }
    // The specification's pad bytes, alternating, for whatever room is left.
    for (var p = stream.bits.length / 8; p < symbol.data; p++) {
      out[p] = ((p - stream.bits.length / 8) % 2 === 0) ? 0xEC : 0x11;
    }

    var parity = remainder(out, symbol.ec);
    var all = new Uint8Array(symbol.data + symbol.ec);
    all.set(out, 0);
    all.set(parity, symbol.data);
    return all;
  }

  // ---------------------------------------------------------------- the matrix

  function blank(size) {
    var grid = [];
    for (var y = 0; y < size; y++) {
      grid.push(new Uint8Array(size));
    }
    return grid;
  }

  function drawFunctionPatterns(modules, reserved, version) {
    var size = modules.length;

    function set(row, col, dark) {
      modules[row][col] = dark ? 1 : 0;
      reserved[row][col] = 1;
    }

    // The three finders, each with its separator: a 7x7 eye inside an 8x8 reserved square.
    var corners = [[0, 0], [0, size - 7], [size - 7, 0]];
    for (var c = 0; c < corners.length; c++) {
      var top = corners[c][0];
      var left = corners[c][1];
      for (var dy = -1; dy <= 7; dy++) {
        for (var dx = -1; dx <= 7; dx++) {
          var row = top + dy;
          var col = left + dx;
          if (row < 0 || row >= size || col < 0 || col >= size) continue;
          var ring = Math.max(Math.abs(dy - 3), Math.abs(dx - 3));
          set(row, col, ring !== 2 && ring <= 3);
        }
      }
    }

    // Timing patterns: alternating modules along row 6 and column 6.
    for (var i = 8; i < size - 8; i++) {
      set(6, i, i % 2 === 0);
      set(i, 6, i % 2 === 0);
    }

    // Alignment patterns: a 5x5 target at every pair of centres, minus the three that would sit on
    // a finder.
    var centres = ALIGNMENT[version];
    for (var a = 0; a < centres.length; a++) {
      for (var b = 0; b < centres.length; b++) {
        var cy = centres[a];
        var cx = centres[b];
        var onFinder = (cy === 6 && cx === 6)
            || (cy === 6 && cx === size - 7)
            || (cy === size - 7 && cx === 6);
        if (onFinder) continue;
        for (var ay = -2; ay <= 2; ay++) {
          for (var ax = -2; ax <= 2; ax++) {
            set(cy + ay, cx + ax, Math.max(Math.abs(ay), Math.abs(ax)) !== 1);
          }
        }
      }
    }

    // The one module that is always dark, and the two strips the format information will occupy.
    set(size - 8, 8, true);
    for (var f = 0; f <= 8; f++) {
      if (!reserved[8][f]) set(8, f, false);
      if (!reserved[f][8]) set(f, 8, false);
    }
    for (var g = 0; g < 8; g++) {
      if (!reserved[size - 1 - g][8]) set(size - 1 - g, 8, false);
      if (!reserved[8][size - 1 - g]) set(8, size - 1 - g, false);
    }
  }

  /** The data bits, snaked up and down two-module columns from the bottom right. */
  function placeData(modules, reserved, data) {
    var size = modules.length;
    var bit = 0;
    var total = data.length * 8;

    for (var right = size - 1; right >= 1; right -= 2) {
      if (right === 6) right = 5;           // column 6 is the vertical timing pattern
      // Column pairs alternate direction, and the pair holding the bottom-right corner goes up.
      var upward = ((right + 1) & 2) === 0;
      for (var step = 0; step < size; step++) {
        var row = upward ? size - 1 - step : step;
        for (var j = 0; j < 2; j++) {
          var col = right - j;
          if (reserved[row][col]) continue;
          if (bit < total) {
            modules[row][col] = (data[bit >>> 3] >>> (7 - (bit & 7))) & 1;
            bit++;
          } else {
            modules[row][col] = 0;          // remainder bits, always light
          }
        }
      }
    }
  }

  var MASKS = [
    function (r, c) { return (r + c) % 2 === 0; },
    function (r) { return r % 2 === 0; },
    function (r, c) { return c % 3 === 0; },
    function (r, c) { return (r + c) % 3 === 0; },
    function (r, c) { return (Math.floor(r / 2) + Math.floor(c / 3)) % 2 === 0; },
    function (r, c) { return (r * c) % 2 + (r * c) % 3 === 0; },
    function (r, c) { return ((r * c) % 2 + (r * c) % 3) % 2 === 0; },
    function (r, c) { return ((r + c) % 2 + (r * c) % 3) % 2 === 0; }
  ];

  function applyMask(modules, reserved, mask) {
    var rule = MASKS[mask];
    for (var r = 0; r < modules.length; r++) {
      for (var c = 0; c < modules.length; c++) {
        if (!reserved[r][c] && rule(r, c)) modules[r][c] ^= 1;
      }
    }
  }

  /** The 15-bit format information: two BCH-protected copies of the level and the mask. */
  function drawFormat(modules, reserved, level, mask) {
    var size = modules.length;
    var value = (LEVEL_BITS[level] << 3) | mask;
    // Ten rounds of the BCH(15,5) generator 0x537, then the specification's fixed mask so that a
    // symbol whose level and mask are both zero is not a run of fifteen light modules.
    var rest = value;
    for (var i = 0; i < 10; i++) {
      rest = (rest << 1) ^ ((rest >>> 9) * 0x537);
    }
    var bits = ((value << 10) | rest) ^ 0x5412;

    function bit(n) { return (bits >>> n) & 1; }
    function set(row, col, v) { modules[row][col] = v; reserved[row][col] = 1; }

    /*
      Both copies, in (row, column). Bit 0 is the last parity bit and bit 14 the first level bit;
      the specification's own figure runs bit 14 along row 8 from column 0 and bit 0 up column 8
      from row 0, which is why the two loops below look lopsided. Column 6 and row 6 are skipped
      for free: the ranges below step around them.
    */
    for (var a = 0; a <= 5; a++) set(a, 8, bit(a));
    set(7, 8, bit(6));
    set(8, 8, bit(7));
    set(8, 7, bit(8));
    for (var b = 9; b < 15; b++) set(8, 14 - b, bit(b));

    for (var c = 0; c < 8; c++) set(8, size - 1 - c, bit(c));
    for (var d = 8; d < 15; d++) set(size - 15 + d, 8, bit(d));
    set(size - 8, 8, 1);                    // the always-dark module, restated
  }

  // ---------------------------------------------------------------- mask scoring

  function penalty(modules) {
    var size = modules.length;
    var score = 0;
    var r, c, run, i;

    // Rule 1: runs of five or more of the same colour, in both directions.
    for (r = 0; r < size; r++) {
      run = 1;
      for (c = 1; c < size; c++) {
        if (modules[r][c] === modules[r][c - 1]) {
          run++;
          if (run === 5) score += 3; else if (run > 5) score += 1;
        } else {
          run = 1;
        }
      }
    }
    for (c = 0; c < size; c++) {
      run = 1;
      for (r = 1; r < size; r++) {
        if (modules[r][c] === modules[r - 1][c]) {
          run++;
          if (run === 5) score += 3; else if (run > 5) score += 1;
        } else {
          run = 1;
        }
      }
    }

    // Rule 2: every 2x2 block of one colour.
    for (r = 0; r < size - 1; r++) {
      for (c = 0; c < size - 1; c++) {
        var v = modules[r][c];
        if (v === modules[r][c + 1] && v === modules[r + 1][c] && v === modules[r + 1][c + 1]) {
          score += 3;
        }
      }
    }

    // Rule 3: the finder-lookalike 1:1:3:1:1 with four light modules on either side.
    var a = [1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0];
    var b = [0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1];
    function matches(line, at, pattern) {
      for (var k = 0; k < pattern.length; k++) {
        if (line[at + k] !== pattern[k]) return false;
      }
      return true;
    }
    for (r = 0; r < size; r++) {
      var row = modules[r];
      for (c = 0; c + 11 <= size; c++) {
        if (matches(row, c, a) || matches(row, c, b)) score += 40;
      }
    }
    for (c = 0; c < size; c++) {
      var column = new Uint8Array(size);
      for (r = 0; r < size; r++) column[r] = modules[r][c];
      for (r = 0; r + 11 <= size; r++) {
        if (matches(column, r, a) || matches(column, r, b)) score += 40;
      }
    }

    // Rule 4: how far the proportion of dark modules strays from half.
    var dark = 0;
    for (r = 0; r < size; r++) {
      for (c = 0; c < size; c++) dark += modules[r][c];
    }
    var percent = (dark * 100) / (size * size);
    score += Math.floor(Math.abs(percent - 50) / 5) * 10;

    return score;
  }

  // ---------------------------------------------------------------- the public part

  /**
   * Encodes `text` and returns `{ size, version, level, mask, modules }`, where `modules[row][col]`
   * is 1 for a dark module. No quiet zone: that is the caller's margin to draw.
   */
  function encode(text, options) {
    var level = (options && options.level) || 'M';
    var bytes = toBytes(String(text));
    var symbol = chooseSymbol(bytes.length, level);
    var data = codewords(bytes, symbol);
    var size = symbol.version * 4 + 17;

    var best = null;
    for (var mask = 0; mask < 8; mask++) {
      var modules = blank(size);
      var reserved = blank(size);
      drawFunctionPatterns(modules, reserved, symbol.version);
      placeData(modules, reserved, data);
      applyMask(modules, reserved, mask);
      drawFormat(modules, reserved, symbol.level, mask);
      var score = penalty(modules);
      if (!best || score < best.score) {
        best = { score: score, mask: mask, modules: modules };
      }
    }

    return {
      size: size,
      version: symbol.version,
      level: symbol.level,
      mask: best.mask,
      modules: best.modules
    };
  }

  /**
   * The same thing as an SVG string, one path for every dark run in a row.
   *
   * `quiet` is the margin in modules. The specification asks for four; a caller drawing the code on
   * a white tile that already has padding of its own may pass less, and the page does.
   */
  function svg(text, options) {
    var settings = options || {};
    var code = encode(text, settings);
    var quiet = settings.quiet === undefined ? 4 : settings.quiet;
    var span = code.size + quiet * 2;
    var dark = settings.dark || '#0F172A';
    var light = settings.light || '#FFFFFF';
    var title = settings.title;

    var path = '';
    for (var r = 0; r < code.size; r++) {
      var c = 0;
      while (c < code.size) {
        if (!code.modules[r][c]) { c++; continue; }
        var run = 0;
        while (c + run < code.size && code.modules[r][c + run]) run++;
        path += 'M' + (c + quiet) + ' ' + (r + quiet) + 'h' + run + 'v1h-' + run + 'z';
        c += run;
      }
    }

    return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ' + span + ' ' + span + '"'
        + ' shape-rendering="crispEdges"'
        + (title ? ' role="img" aria-label="' + escapeAttribute(title) + '"' : ' aria-hidden="true"')
        + '>'
        + '<rect width="' + span + '" height="' + span + '" fill="' + light + '"/>'
        + '<path d="' + path + '" fill="' + dark + '"/>'
        + '</svg>';
  }

  function escapeAttribute(value) {
    return String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;')
        .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  }

  var api = { encode: encode, svg: svg };

  if (typeof module === 'object' && module.exports) {
    module.exports = api;          // so the check in infra can require it
  }
  global.YouDropQR = api;
})(typeof window !== 'undefined' ? window : this);
