#!/bin/sh
# Rotate the onboarding-service client secret. Runs inside a throwaway container that has curl+jq.
#
# ONBOARDING_CLIENT_SECRET was never set in .env, so compose fell back to the literal in
# docker-compose.dev.yml — which is published in a PUBLIC repository. That service account holds
# BACKOFFICE, manage-users and view-realm, and Keycloak answers on the public internet, so the
# fallback was a working platform-administrator credential anybody could read and use.
#
# Keycloak generates the replacement. This script never chooses it and never echoes it.
set -eu
apk add --no-cache curl jq >/dev/null 2>&1
cd /w

KC=https://iam-dev.youdrop.shop
REALM=delivery-platform
CLIENT=onboarding-service

ADMIN_USER=$(grep -E '^KEYCLOAK_ADMIN=' .env | cut -d= -f2-)
ADMIN_PASS=$(grep -E '^KEYCLOAK_ADMIN_PASSWORD=' .env | cut -d= -f2-)
[ -n "$ADMIN_USER" ] && [ -n "$ADMIN_PASS" ] || { echo "FAILED: no Keycloak admin credentials in .env"; exit 1; }

TOKEN=$(curl -sf -X POST "$KC/realms/master/protocol/openid-connect/token" \
  -d client_id=admin-cli -d grant_type=password \
  --data-urlencode "username=$ADMIN_USER" --data-urlencode "password=$ADMIN_PASS" \
  | jq -r '.access_token // empty')
[ -n "$TOKEN" ] || { echo "FAILED: could not get a Keycloak admin token"; exit 1; }
echo "admin token acquired"

CID=$(curl -sf "$KC/admin/realms/$REALM/clients?clientId=$CLIENT" \
  -H "Authorization: Bearer $TOKEN" | jq -r '.[0].id // empty')
[ -n "$CID" ] || { echo "FAILED: client $CLIENT not found"; exit 1; }
echo "client located: $CID"

NEW=$(curl -sf -X POST "$KC/admin/realms/$REALM/clients/$CID/client-secret" \
  -H "Authorization: Bearer $TOKEN" | jq -r '.value // empty')
# A real Keycloak secret is a long opaque string. Anything else must not reach .env.
case "$NEW" in
  '' ) echo "FAILED: Keycloak returned no secret"; exit 1 ;;
esac
[ ${#NEW} -ge 20 ] || { echo "FAILED: returned secret is implausibly short"; exit 1; }
echo "new secret generated by Keycloak (${#NEW} chars, not shown)"

cp .env ".env.bak.rotate"
grep -v '^ONBOARDING_CLIENT_SECRET=' .env > .env.tmp || true
printf 'ONBOARDING_CLIENT_SECRET=%s\n' "$NEW" >> .env.tmp
mv .env.tmp .env
chmod 600 .env
echo "written to .env (mode 600; previous saved as .env.bak.rotate)"
